version: '3.9'

services:
  postgres:
    image: 'postgres:alpine'
    container_name: database-algafood
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_DB: 'algafood'